#!/bin/bash
# =============================================================================
# Secure Drop VPS/EC2 Deployment Script
# Run this on your server after files are copied
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Secure Drop Deployment ===${NC}"

# Change to script directory
cd "$(dirname "$0")"

# Detect server IP if not set
if [ -z "$SERVER_IP" ]; then
    SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s icanhazip.com 2>/dev/null || echo "")
    if [ -z "$SERVER_IP" ]; then
        echo -e "${RED}Could not detect server IP. Please set SERVER_IP environment variable.${NC}"
        exit 1
    fi
fi

echo -e "${YELLOW}Server IP: ${SERVER_IP}${NC}"

# Determine if using domain or IP
if [ -n "$DOMAIN" ]; then
    echo -e "${YELLOW}Domain: ${DOMAIN}${NC}"
    APP_URL="https://${DOMAIN}"
    FRONTEND_URL="https://${DOMAIN}"
else
    echo -e "${YELLOW}No domain set, using IP address${NC}"
    APP_URL="http://${SERVER_IP}"
    FRONTEND_URL="http://${SERVER_IP}"
fi

echo -e "${YELLOW}APP_URL: ${APP_URL}${NC}"
echo -e "${YELLOW}FRONTEND_URL: ${FRONTEND_URL}${NC}"

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo -e "${YELLOW}Creating .env file...${NC}"
    cat > .env << EOF
# Auto-generated by deploy.sh
APP_URL=${APP_URL}
FRONTEND_URL=${FRONTEND_URL}
EOF

    # Add ACME email if domain is set
    if [ -n "$DOMAIN" ] && [ -n "$ACME_EMAIL" ]; then
        echo "ACME_EMAIL=${ACME_EMAIL}" >> .env
    fi

    echo -e "${GREEN}Created .env file${NC}"
else
    echo -e "${YELLOW}Updating existing .env file...${NC}"
    # Update existing .env with new values
    sed -i "s|^APP_URL=.*|APP_URL=${APP_URL}|" .env 2>/dev/null || true
    sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=${FRONTEND_URL}|" .env 2>/dev/null || true
fi

# Stop and remove existing containers completely
echo -e "${YELLOW}Stopping and removing existing containers...${NC}"
docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans 2>/dev/null || true

# Remove old containers and networks to ensure clean state
echo -e "${YELLOW}Cleaning up old containers...${NC}"
docker container prune -f 2>/dev/null || true

# Build and start containers with force recreate
echo -e "${YELLOW}Building and starting containers...${NC}"
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --force-recreate

# Wait for containers to be healthy
echo -e "${YELLOW}Waiting for containers to be healthy...${NC}"
sleep 10

# Run migrations
echo -e "${YELLOW}Running database migrations...${NC}"
docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T api php artisan migrate --force || echo "Migration may have already run"

# Clear cache
echo -e "${YELLOW}Clearing application cache...${NC}"
docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T api php artisan cache:clear || true
docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T api php artisan config:clear || true

# Show status
echo ""
echo -e "${GREEN}=== Deployment Complete ===${NC}"
docker compose ps

echo ""
echo -e "${GREEN}Your application is now live!${NC}"
echo -e "Access at: ${APP_URL}"
echo ""
echo -e "${YELLOW}Useful commands:${NC}"
echo "  docker compose logs -f        # View logs"
echo "  docker compose ps             # Check status"
echo "  docker compose restart        # Restart services"
echo "  docker compose down           # Stop services"
